AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 bucket and DynamoDB table


Resources:

###########
# S3 Bucket
###########

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hiit-cloudformation-bucket-2022

###########
# DynamoDB table
###########

  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: Artist
          AttributeType: S
        - 
          AttributeName: SongTitle
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - 
          AttributeName: Artist
          KeyType: HASH
        - 
          AttributeName: SongTitle
          KeyType: RANGE
      TableName: Music


  

